# Write your MySQL query statement below
SELECT 
    DATE_FORMAT(TRANS_DATE,'%Y-%m') AS MONTH,country, 
    COUNT(*) AS TRANS_COUNT,
    SUM(CASE WHEN STATE ="APPROVED" THEN 1 ELSE 0 END) AS APPROVED_COUNT,
    SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
    SUM(CASE WHEN STATE="APPROVED" THEN AMOUNT ELSE 0 END) AS APPROVED_TOTAL_AMOUNT
FROM transactions t
GROUP BY  DATE_FORMAT(trans_date, '%Y-%m'),COUNTRY;